(require 'modern-common)

(deftheme modern-dawn "Modern theme, the dawn version")

(let (
            (class '((class color) (min-colors 89)))
            (act1          "#18303F")
            (act2          "#18303F")
            (base          "#C9BAAC")
            (base-b        "#DDD1C6")
            (base-dim      "#AAA198")
            (bg1           "#101F29")
            (bg2           "#132632")
            (bg3           "#18303F")
            (bg4           "#214054")
            (border        "#18303F")

            (cblk          "#AAA198")
            (cblk-bg       "#18303F")
            (cblk-ln       "#519CCD")
            (cblk-ln-bg    "#214054")
            (cursor        "#648DFF")
            (const         "#8CB6E1")
            (comment       "#519CCD")
            (comment-light "#519CCD")
            (comment-bg    "#18303F")
            (comp          "#D87184")
            (err           "#E46261")
            (func          "#648DFF")

            (highlight     "#648DFF")
            (highlight-dim "#8CB6E1")
            (keyword       "#648DFF")
            (lnum          "#44505c")
            (str           "#64C2FF")
            (suc           "#82D88F")
            (ttip          "#DDD1C6")
            (ttip-sl       "#2C5672")
            (ttip-bg       "#214054")
            (type          "#9C75ED")
            (var           "#FFED6A")
            (war           "#DC9E66")

            ;; colors
            (aqua          "#DC9E66")
            (aqua-l        "#C79C77")
            (aqua-d        "#F1AD4D")
            (aqua-bg       "#4E3824")
            (green         "#82D88F")
            (green-l       "#7FB087")
            (green-d       "#99DA63")
            (green-bg      "#326046")
            (green-bg-s    "#224630")
            (red           "#D87184")
            (red-l         "#BB7B86")
            (red-d         "#E46261")
            (red-bg        "#422328")
            (red-bg-s      "#572926")
            (blue          "#1E95CC")
            (blue-l        "#519CCD")
            (blue-d        "#648DFF")
            (blue-bg       "#214054")
            (magenta       "#8778D8")
            (magenta-l     "#837EB9")
            (magenta-d     "#9C75ED")
            (magenta-bg    "#2E2949")
            (yellow        "#FFED6A")
            (yellow-l      "#EADC77")
            (yellow-d      "#FFDA53")
            (yellow-bg     "#575124")
            )
  (create-modern-theme 'modern-dawn)
  (provide-theme 'modern-dawn)
)

